export const ACTION_ITEM_CHECKLIST_ITEMS = [
  { category: "Underwriting Document", item: "Background", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Underwriting Document", item: "Credit", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Underwriting Document", item: "Appraisal/Valuation", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Underwriting Document", item: "Contractor/Scope", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction"] },
  { category: "Underwriting Document", item: "Title", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Underwriting Document", item: "Send Indicative Terms", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Legal Document", item: "Legal Docs", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Processing", item: "Appraisal Fee Request", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Processing", item: "Schedule Appraisal", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Processing", item: "Schedule Title", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Processing", item: "Schedule Background", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Processing", item: "Schedule Insurance", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Processing", item: "Appraisal Received", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Processing", item: "Term Sheet Final", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Processing", item: "Background Received", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Processing", item: "Final Terms Agreed", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Processing", item: "Final CD", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Processing", item: "Schedule Closing", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Invoice Title/Attorney", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Invoice Appraisal", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Warehouse Advance", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Send to Servicer", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Send to Buyer", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"] }
];

export const DOCUMENT_CHECKLIST_ITEMS = [
  { category: "Borrower Document", item: "Photo ID", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Driver's License or other government-issued photo ID" },
  { category: "Borrower Document", item: "Track Record", provider: "Borrower", loan_types: ["Fix & Flip", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Real estate investment sales in the last 36 months" },
  { category: "Borrower Document", item: "Experience Verification Docs", provider: "Borrower", loan_types: ["Fix & Flip", "Refinance", "New Construction"], description: "HUD, Deed, MLS/Tax Records, or other verifiable sources" },
  { category: "Borrower Document", item: "Signed Loan Application", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Borrower Document", item: "Borrower Authorization", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Needed to run credit and background check" },
  { category: "Borrower Document", item: "Proof of Liquidity", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Most recent 3 months bank/asset statements" },
  { category: "Borrower Document", item: "Certificates of formation/ Articles of organization/incorporation", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Borrower Document", item: "Operating agreement / Partnership Agreement / Bylaws", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Borrower Document", item: "EIN Letter", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Borrower Document", item: "Certificate of Good Standing (Dated within 90 Days from Origination)", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Required only if formed more than a year ago" },
  { category: "Borrower Document", item: "Banking Info", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Bank-issued docs showing routing numbers, account number, bank name, account holder name" },
  { category: "Borrower Document", item: "Personal Financial Statement", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction"], description: "Required if loan amount is greater than $1M" },
  { category: "Borrower Document", item: "Credit Report", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Borrower Document", item: "Background Check", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Borrower Document", item: "OFAC Result", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Purchase Contract or Proof of Ownership", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Deed or Purchase HUD (Signed)" },
  { category: "Property Document", item: "Scope of Work / Rehab Budget", provider: "Borrower", loan_types: ["Fix & Flip", "New Construction", "Refinance"], description: "" },
  { category: "Property Document", item: "Evidence of Insurance", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "For Condominium, Master Insurance Policy/Certificate is needed" },
  { category: "Property Document", item: "Flood Insurance", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Required only if flood zone" },
  { category: "Property Document", item: "General Contractor Information", provider: "Borrower", loan_types: ["Fix & Flip", "Refinance", "New Construction"], description: "Contractor's License and Contact Information" },
  { category: "Property Document", item: "Signed Lease Agreement", provider: "Borrower", loan_types: ["DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Proof of Security Deposit and 1st Month's Rent", provider: "Borrower", loan_types: ["DSCR Purchase", "DSCR Refinance"], description: "Required for new leases effective within 60 days prior to origination" },
  { category: "Property Document", item: "Proof of Rent Collection", provider: "Borrower", loan_types: ["DSCR Purchase", "DSCR Refinance"], description: "Required for month-to-month leases; Most recent 6 consecutive months rent" },
  { category: "Property Document", item: "Payoff Letter", provider: "Borrower", loan_types: ["Refinance", "DSCR Refinance"], description: "From the current lender" },
  { category: "Property Document", item: "Verification of Mortgage", provider: "Borrower", loan_types: ["Refinance", "DSCR Refinance"], description: "From the current lender, showing payment history" },
  { category: "Property Document", item: "Condominium Questionnaire", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Required if condo" },
  { category: "Property Document", item: "Permits", provider: "Borrower", loan_types: ["New Construction"], description: "" },
  { category: "Property Document", item: "Architectural Plan", provider: "Borrower", loan_types: ["Fix & Flip", "Refinance", "New Construction"], description: "For Fix & Flip: Required if addition is involved" },
  { category: "Property Document", item: "Rent Roll & Unit Mix", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction"], description: "If Multi-family" },
  { category: "Property Document", item: "LTM and Pro forma P&L Statement", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction"], description: "If Multi-family" },
  { category: "Property Document", item: "Entitlement or Zoning Verification Letter", provider: "Borrower", loan_types: ["New Construction"], description: "" },
  { category: "Property Document", item: "Survey", provider: "Borrower", loan_types: ["New Construction"], description: "" },
  { category: "Property Document", item: "Property Insurance", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Appraisal", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Valuation Review", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Required if Multifamily, Mixed Use, or Ground-up Construction" },
  { category: "Property Document", item: "Rural / Population Check", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Feasibility Review", provider: "Amplend", loan_types: ["Fix & Flip", "Refinance", "New Construction"], description: "For Fix&Flip: Required if Rehab Budget is greater than $150,000 or greater than 50% of Purchase Price. For GUC: Always required" },
  { category: "Property Document", item: "Environmental Screen", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction"], description: "If Multi-family or Mixed Use" },
  { category: "Property Document", item: "Tax Certificate", provider: "Amplend", loan_types: ["DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Flood Certificate", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Contractor Review", provider: "Amplend", loan_types: ["New Construction"], description: "Minimum of 5 ground-up projects within the past 3 years" },
  { category: "Closing Document", item: "ACH Form", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "Loan Docs", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "Initial Payment Notice", provider: "Amplend", loan_types: ["DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "HUD", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "Title Commitment", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "Closing Protection Letter", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "Deed", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase"], description: "" },
  { category: "Closing Document", item: "Title E&O", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "Title Wiring Info", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Post-Closing Document", item: "Recorded Mortgage", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Post-Closing Document", item: "Recorded AOM", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Post-Closing Document", item: "Recorded ALR", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Post-Closing Document", item: "Recorded Deed", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase"], description: "" },
  { category: "Post-Closing Document", item: "Final Title Policy", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" }
];