export const ACTION_ITEM_CHECKLIST_ITEMS = [
  { category: "Lead", item: "Population Test | Rural Check", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Lead", item: "3 Comps Sold within 6 Months and 1 Mile or Same Zip Code", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Lead", item: "Minimum Property Value", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Lead", item: "Minimum SQFT", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Lead", item: "0-2 Experience Borrower - Baltimore or Philadelphia", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "Lead", item: "Seasoning Period Check", loan_types: ["Fix & Flip Refinance", "Bridge Refinance", "New Construction Refinance", "DSCR Refinance"] },
  { category: "Lead", item: "Sizer Completion (Excel & Online)", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Lead", item: "Pre-Appraisal Term Sheet Sent to Borrower", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Lead", item: "Go-signal from Borrower via Email", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Order Outs", item: "Appraisal Order", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Order Outs", item: "Title Search Order", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Order Outs", item: "Feasibility Study Order (if Heavy Rehab)", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "Order Outs", item: "Environmental Screen Order (if required for MF & Mixed-Use)", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "Order Outs", item: "Valuation Review Order", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Order Outs", item: "Property Insurance Quote Request", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Order Outs", item: "Flood Insurance Quote Request (only if Flood zone)", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Purchase Agreement", item: "Purchase Price Correctly Input into Sizer", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Purchase Agreement", item: "Buyer Name = Borrower", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Purchase Agreement", item: "Seller Name = Owner of Record", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Purchase Agreement", item: "Executed / Signed by All Parties", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Purchase Agreement", item: "Confirm the Presence of Assignment and Validate", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Purchase Agreement", item: "Valid Closing Date", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Purchase Agreement", item: "Proper Chain in Assignment of Contract (if applicable)", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "SOW", item: "Rehab Budget Correctly Input into Sizer", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "SOW", item: "Listed Items Descriptive Enough", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "SOW", item: "Final Confirmation with Borrower Before Closing", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "Credit / Background", item: "Age of Report Less Than 90 days", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Credit / Background", item: "Minimum Credit Score", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Credit / Background", item: "No Current Mortgage DQ or DQ of 60+ in past 24 months", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Credit / Background", item: "No Short Sale, Deed-in-Lieu, or Bankruptcy in past 36 months", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Credit / Background", item: "LOE on Open Liens, Judgments, Criminal Records with Supporting Docs", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "OFAC", item: "Borrowers and Borrowing Entity Not Listed", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Photo ID", item: "Name & Mailing Address Present / Not Expired", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Track Record", item: "Experiences Verified Through Reliable Sources", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Appraisal Report", item: "Age of Report Less Than 90 Days", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Appraisal Report", item: "Owner of Record = Seller Name", loan_types: ["Fix & Flip Purchase", "Bridge Purchase", "New Construction Purchase", "DSCR Purchase"] },
  { category: "Appraisal Report", item: "Owner of Record = Borrower Name", loan_types: ["Fix & Flip Refinance", "Bridge Refinance", "New Construction Refinance", "DSCR Refinance"] },
  { category: "Appraisal Report", item: "Location Check [i.e. Urban or Suburban]", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Appraisal Report", item: "Property Values [i.e. Increasing or Stable]", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Appraisal Report", item: "Zoning Compliance [i.e. Legal or Legal Nonconforming]", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Appraisal Report", item: "3 Comps within 1 Mile or Same Zip Code", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Appraisal Report", item: "3 Comps Sold within 6 Months", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Appraisal Report", item: "Appraisal and Post-Appraisal Term Sheet Sent to Borrower", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Appraisal Report", item: "Appraised Values Correctly Input into Sizer", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Appraisal Report", item: "Oil Tank", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Appraisal Report", item: "1.) Cost to Cure 2.) Deferred Maintenance 3.) Mold 4.) Obsolescence", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Feasibility for Heavy Rehab", item: "Budget is Sufficient for Project", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "Feasibility for Heavy Rehab", item: "Feedback Sent to Borrower, if needed", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "GC Info for Newbie Borrower", item: "GC License", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "GC Info for Newbie Borrower", item: "Contract between GC and Borrower", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "GC Info for Newbie Borrower", item: "GC General Liability Insurance Coverage Confirmation", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "Flood Certificate", item: "Borrower and Subject Property Confirmation", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Flood Certificate", item: "Flood Zone Check", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Flood Certificate", item: "\"Life of Loan Determination\" in Comments Section", loan_types: ["DSCR Refinance", "DSCR Purchase"] },
  { category: "Liquidity", item: "Account Holder's Name Matched or Verified through Entity Docs", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Liquidity", item: "Large Deposits Verified (i.e. more than 50% of required liquidity)", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Liquidity", item: "Minimum Liquidity Requirement Met", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Liquidity", item: "Statement Less than 45 Days Old from Closing", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Property Insurance", item: "Insured Name and Property Address Confirmiaton", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Property Insurance", item: "Loan Funding Group II LLC, ISAOA/ATIMA as Mortgagee", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Property Insurance", item: "Insurance Agent's Signature Present", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Property Insurance", item: "Dwelling Coverage \u2265 Loan Amount", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Property Insurance", item: "General Liability Coverage (Min $500,000)", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Property Insurance", item: "Insurance Invoice or Payment Receipt", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Property Insurance", item: "RCV, Special/Broad Form or DP3", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Property Insurance", item: "12 Months for Purchase or More than 60 Days Left for Refi", loan_types: ["DSCR Refinance", "DSCR Purchase"] },
  { category: "Property Insurance", item: "Rent Loss Covering 6 Months or More", loan_types: ["DSCR Refinance", "DSCR Purchase"] },
  { category: "Property Insurance", item: "6 Months for Purchase or More than 60 Days Left for Refi", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "Property Insurance", item: "Builder's Risk Insurance Coverage", loan_types: ["Fix & Flip", "Bridge", "New Construction"] },
  { category: "Title Docs", item: "Loan Funding Group II LLC, ISAOA/ATIMA on Title Commitment and CPL", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Title Docs", item: "Purchase Price and Loan Amount on Title Commitment", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Title Docs", item: "Title Reivew Clearance - Lender and Attorney", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Title Docs", item: "Title Reivew Clearance - Title Company", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Lease", item: "Landlord Name Matching Borrower or Entity", loan_types: ["DSCR Refinance", "DSCR Purchase"] },
  { category: "Lease", item: "Executed / Signed by all parties", loan_types: ["DSCR Refinance", "DSCR Purchase"] },
  { category: "Lease", item: "For New Lease, Proof of Rent Collection and Security Deposit", loan_types: ["DSCR Refinance", "DSCR Purchase"] },
  { category: "Lease", item: "Occupancy Determination", loan_types: ["DSCR Refinance", "DSCR Purchase"] },
  { category: "Proof of Ownership / Purchase HUD", item: "Buyer Name = Borrower", loan_types: ["Fix & Flip Refinance", "Bridge Refinance", "New Construction Refinance", "DSCR Refinance"] },
  { category: "Proof of Ownership / Purchase HUD", item: "Property Address Match", loan_types: ["Fix & Flip Refinance", "Bridge Refinance", "New Construction Refinance", "DSCR Refinance"] },
  { category: "Proof of Ownership / Purchase HUD", item: "Existence of Loan Check (i.e. Seasoning Period Impact)", loan_types: ["Fix & Flip Refinance", "Bridge Refinance", "New Construction Refinance", "DSCR Refinance"] },
  { category: "Payoff Statement", item: "Subject Property Address Matching", loan_types: ["Fix & Flip Refinance", "Bridge Refinance", "New Construction Refinance", "DSCR Refinance"] },
  { category: "Payoff Statement", item: "Borrowers / Borrowing Entity Matching", loan_types: ["Fix & Flip Refinance", "Bridge Refinance", "New Construction Refinance", "DSCR Refinance"] },
  { category: "Payoff Statement", item: "Valid Good-Through Date", loan_types: ["Fix & Flip Refinance", "Bridge Refinance", "New Construction Refinance", "DSCR Refinance"] },
  { category: "VOM/Payment History", item: "Subject Property Address Matching", loan_types: ["Fix & Flip Refinance", "Bridge Refinance", "New Construction Refinance", "DSCR Refinance"] },
  { category: "VOM/Payment History", item: "Borrowers / Borrowing Entity Matching", loan_types: ["Fix & Flip Refinance", "Bridge Refinance", "New Construction Refinance", "DSCR Refinance"] },
  { category: "VOM/Payment History", item: "No Late Payments or Delinquency", loan_types: ["Fix & Flip Refinance", "Bridge Refinance", "New Construction Refinance", "DSCR Refinance"] },
  { category: "Closing", item: "CTC from Amplend and LHRG, including Title Docs", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Closing", item: "CTC from Title", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Closing", item: "Closing Date/Time Set Up", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Closing", item: "RAI Funding Request", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Closing", item: "Loop Email with Title, Borrower, Seller, and LHRG", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Closing", item: "HUD Finalized", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Closing", item: "Loan Docs Draft Prepared and Received", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Closing", item: "Loan Docs Draft Reviewed and Approved", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Closing", item: "Pre-Close Prep Call or Email with Borrower", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Closing", item: "Executed Loan Docs Received", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Closing", item: "Funding Approval Granted", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Closing", item: "Loan Funded", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Congratulatory/Gratitude Email to Borrower and Partners", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Commissions Paid Out", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Recorded Mortgage Received", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Recorded ALR Received", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Recorded AOM (and AALR) Received", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Title Policy Received", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Trailing Documents Cleared by Loan Buyer", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Payoff Letter Requested", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Payoff Letter Sent to Borrower After Checking Validity", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
  { category: "Post-Close", item: "Unrecording Docs After Payoff", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase", "DSCR Refinance"] },
];

export const DOCUMENT_CHECKLIST_ITEMS = [
  { category: "Borrower Document", item: "Photo ID", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Driver's License or other government-issued photo ID" },
  { category: "Borrower Document", item: "Track Record", provider: "Borrower", loan_types: ["Fix & Flip", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Real estate investment sales in the last 36 months" },
  { category: "Borrower Document", item: "Experience Verification Docs", provider: "Borrower", loan_types: ["Fix & Flip", "Refinance", "New Construction"], description: "HUD, Deed, MLS/Tax Records, or other verifiable sources" },
  { category: "Borrower Document", item: "Signed Loan Application", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Borrower Document", item: "Borrower Authorization", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Needed to run credit and background check" },
  { category: "Borrower Document", item: "Proof of Liquidity", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Most recent 3 months bank/asset statements" },
  { category: "Borrower Document", item: "Certificates of formation/ Articles of organization/incorporation", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Borrower Document", item: "Operating agreement / Partnership Agreement / Bylaws", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Borrower Document", item: "EIN Letter", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Borrower Document", item: "Certificate of Good Standing (Dated within 90 Days from Origination)", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Required only if formed more than a year ago" },
  { category: "Borrower Document", item: "Banking Info", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Bank-issued docs showing routing numbers, account number, bank name, account holder name" },
  { category: "Borrower Document", item: "Personal Financial Statement", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction"], description: "Required if loan amount is greater than $1M" },
  { category: "Borrower Document", item: "Credit Report", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Borrower Document", item: "Background Check", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Borrower Document", item: "OFAC Result", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Purchase Contract or Proof of Ownership", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Deed or Purchase HUD (Signed)" },
  { category: "Property Document", item: "Scope of Work / Rehab Budget", provider: "Borrower", loan_types: ["Fix & Flip", "New Construction", "Refinance"], description: "" },
  { category: "Property Document", item: "Evidence of Insurance", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "For Condominium, Master Insurance Policy/Certificate is needed" },
  { category: "Property Document", item: "Flood Insurance", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Required only if flood zone" },
  { category: "Property Document", item: "General Contractor Information", provider: "Borrower", loan_types: ["Fix & Flip", "Refinance", "New Construction"], description: "Contractor's License and Contact Information" },
  { category: "Property Document", item: "Signed Lease Agreement", provider: "Borrower", loan_types: ["DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Proof of Security Deposit and 1st Month's Rent", provider: "Borrower", loan_types: ["DSCR Purchase", "DSCR Refinance"], description: "Required for new leases effective within 60 days prior to origination" },
  { category: "Property Document", item: "Proof of Rent Collection", provider: "Borrower", loan_types: ["DSCR Purchase", "DSCR Refinance"], description: "Required for month-to-month leases; Most recent 6 consecutive months rent" },
  { category: "Property Document", item: "Payoff Letter", provider: "Borrower", loan_types: ["Refinance", "DSCR Refinance"], description: "From the current lender" },
  { category: "Property Document", item: "Verification of Mortgage", provider: "Borrower", loan_types: ["Refinance", "DSCR Refinance"], description: "From the current lender, showing payment history" },
  { category: "Property Document", item: "Condominium Questionnaire", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Required if condo" },
  { category: "Property Document", item: "Permits", provider: "Borrower", loan_types: ["New Construction"], description: "" },
  { category: "Property Document", item: "Architectural Plan", provider: "Borrower", loan_types: ["Fix & Flip", "Refinance", "New Construction"], description: "For Fix & Flip: Required if addition is involved" },
  { category: "Property Document", item: "Rent Roll & Unit Mix", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction"], description: "If Multi-family" },
  { category: "Property Document", item: "LTM and Pro forma P&L Statement", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction"], description: "If Multi-family" },
  { category: "Property Document", item: "Entitlement or Zoning Verification Letter", provider: "Borrower", loan_types: ["New Construction"], description: "" },
  { category: "Property Document", item: "Survey", provider: "Borrower", loan_types: ["New Construction"], description: "" },
  { category: "Property Document", item: "Property Insurance", provider: "Borrower", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Appraisal", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Valuation Review", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "Required if Multifamily, Mixed Use, or Ground-up Construction" },
  { category: "Property Document", item: "Rural / Population Check", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Feasibility Review", provider: "Amplend", loan_types: ["Fix & Flip", "Refinance", "New Construction"], description: "For Fix&Flip: Required if Rehab Budget is greater than $150,000 or greater than 50% of Purchase Price. For GUC: Always required" },
  { category: "Property Document", item: "Environmental Screen", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction"], description: "If Multi-family or Mixed Use" },
  { category: "Property Document", item: "Tax Certificate", provider: "Amplend", loan_types: ["DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Flood Certificate", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Property Document", item: "Contractor Review", provider: "Amplend", loan_types: ["New Construction"], description: "Minimum of 5 ground-up projects within the past 3 years" },
  { category: "Closing Document", item: "ACH Form", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "Loan Docs", provider: "Amplend", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "Initial Payment Notice", provider: "Amplend", loan_types: ["DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "HUD", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "Title Commitment", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "Closing Protection Letter", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "Deed", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase"], description: "" },
  { category: "Closing Document", item: "Title E&O", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Closing Document", item: "Title Wiring Info", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Post-Closing Document", item: "Recorded Mortgage", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Post-Closing Document", item: "Recorded AOM", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Post-Closing Document", item: "Recorded ALR", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" },
  { category: "Post-Closing Document", item: "Recorded Deed", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "New Construction", "DSCR Purchase"], description: "" },
  { category: "Post-Closing Document", item: "Final Title Policy", provider: "Title Company", loan_types: ["Fix & Flip", "Bridge", "Refinance", "New Construction", "DSCR Purchase", "DSCR Refinance"], description: "" }
];
