// Major counties by state for dropdown selections
export const US_COUNTIES_BY_STATE = {
  "AL": ["Jefferson", "Mobile", "Madison", "Montgomery", "Shelby", "Tuscaloosa", "Baldwin", "Lee", "Lauderdale", "Morgan", "Calhoun", "Etowah", "Houston", "Marshall", "St. Clair"],
  "AK": ["Anchorage", "Fairbanks North Star", "Matanuska-Susitna", "Kenai Peninsula", "Juneau", "Bethel", "Southeast Fairbanks", "Kodiak Island", "Nome", "North Slope"],
  "AZ": ["Maricopa", "Pima", "Pinal", "Yavapai", "Yuma", "Mohave", "Coconino", "Cochise", "Navajo", "Apache", "Gila", "Graham", "Santa Cruz", "La Paz", "Greenlee"],
  "AR": ["Pulaski", "Benton", "Washington", "Sebastian", "Faulkner", "Craighead", "Garland", "Saline", "White", "Lonoke", "Jefferson", "Crawford", "Mississippi", "Pope", "Crittenden"],
  "CA": ["Los Angeles", "San Diego", "Orange", "Riverside", "San Bernardino", "Santa Clara", "Alameda", "Sacramento", "Contra Costa", "Fresno", "Kern", "San Francisco", "Ventura", "San Mateo", "San Joaquin", "Stanislaus", "Sonoma", "Tulare", "Santa Barbara", "Monterey", "Placer", "San Luis Obispo", "Merced", "Santa Cruz", "Marin", "Solano", "Butte", "El Dorado", "Shasta", "Imperial"],
  "CO": ["Denver", "El Paso", "Arapahoe", "Jefferson", "Adams", "Larimer", "Douglas", "Boulder", "Weld", "Pueblo", "Mesa", "Garfield", "Eagle", "La Plata", "Montrose"],
  "CT": ["Fairfield", "Hartford", "New Haven", "New London", "Litchfield", "Middlesex", "Tolland", "Windham"],
  "DE": ["New Castle", "Sussex", "Kent"],
  "FL": ["Miami-Dade", "Broward", "Palm Beach", "Hillsborough", "Orange", "Pinellas", "Duval", "Lee", "Polk", "Brevard", "Volusia", "Pasco", "Seminole", "Sarasota", "Manatee", "Lake", "Collier", "Escambia", "Leon", "Marion", "Osceola", "St. Lucie", "Clay", "Hernando", "St. Johns", "Charlotte", "Alachua", "Bay", "Okaloosa", "Martin"],
  "GA": ["Fulton", "Gwinnett", "Cobb", "DeKalb", "Clayton", "Cherokee", "Forsyth", "Henry", "Chatham", "Richmond", "Columbia", "Muscogee", "Bibb", "Houston", "Hall", "Fayette", "Coweta", "Paulding", "Newton", "Douglas", "Clarke", "Whitfield", "Carroll", "Lowndes", "Barrow"],
  "HI": ["Honolulu", "Hawaii", "Maui", "Kauai", "Kalawao"],
  "ID": ["Ada", "Canyon", "Kootenai", "Bonneville", "Bannock", "Twin Falls", "Nez Perce", "Madison", "Bingham", "Elmore", "Blaine", "Cassia", "Latah", "Payette", "Jerome"],
  "IL": ["Cook", "DuPage", "Lake", "Will", "Kane", "McHenry", "Winnebago", "Madison", "St. Clair", "Champaign", "Sangamon", "Peoria", "Tazewell", "McLean", "Rock Island", "Kendall", "Kankakee", "LaSalle", "DeKalb", "Macon"],
  "IN": ["Marion", "Lake", "Allen", "Hamilton", "St. Joseph", "Elkhart", "Tippecanoe", "Vanderburgh", "Hendricks", "Porter", "Madison", "Vigo", "Johnson", "LaPorte", "Delaware", "Monroe", "Clark", "Hancock", "Floyd", "Bartholomew"],
  "IA": ["Polk", "Linn", "Scott", "Johnson", "Black Hawk", "Woodbury", "Dubuque", "Story", "Pottawattamie", "Dallas", "Warren", "Wapello", "Marshall", "Clinton", "Cerro Gordo"],
  "KS": ["Johnson", "Sedgwick", "Shawnee", "Wyandotte", "Douglas", "Leavenworth", "Riley", "Reno", "Butler", "Saline", "Crawford", "Finney", "Geary", "Lyon", "Cowley"],
  "KY": ["Jefferson", "Fayette", "Kenton", "Boone", "Warren", "Hardin", "Campbell", "Daviess", "Madison", "McCracken", "Christian", "Bullitt", "Oldham", "Pulaski", "Laurel"],
  "LA": ["East Baton Rouge", "Jefferson", "Orleans", "Caddo", "Lafayette", "St. Tammany", "Calcasieu", "Ouachita", "Rapides", "Livingston", "Bossier", "Terrebonne", "Tangipahoa", "Ascension", "Iberia"],
  "ME": ["Cumberland", "York", "Penobscot", "Kennebec", "Androscoggin", "Aroostook", "Oxford", "Somerset", "Knox", "Hancock", "Waldo", "Lincoln", "Sagadahoc", "Franklin", "Washington", "Piscataquis"],
  "MD": ["Montgomery", "Prince George's", "Baltimore County", "Anne Arundel", "Baltimore City", "Howard", "Harford", "Frederick", "Carroll", "Charles", "Washington", "St. Mary's", "Wicomico", "Allegany", "Cecil"],
  "MA": ["Middlesex", "Worcester", "Essex", "Suffolk", "Norfolk", "Bristol", "Plymouth", "Hampden", "Barnstable", "Hampshire", "Berkshire", "Franklin", "Dukes", "Nantucket"],
  "MI": ["Wayne", "Oakland", "Macomb", "Kent", "Genesee", "Washtenaw", "Ottawa", "Ingham", "Kalamazoo", "Livingston", "St. Clair", "Saginaw", "Muskegon", "Monroe", "Jackson", "Berrien", "Allegan", "Lenawee", "Bay", "Calhoun"],
  "MN": ["Hennepin", "Ramsey", "Dakota", "Anoka", "Washington", "St. Louis", "Olmsted", "Scott", "Stearns", "Carver", "Wright", "Blue Earth", "Clay", "Sherburne", "Rice"],
  "MS": ["Hinds", "Harrison", "DeSoto", "Jackson", "Madison", "Rankin", "Lee", "Lauderdale", "Forrest", "Jones", "Lowndes", "Lamar", "Washington", "Warren", "Pearl River"],
  "MO": ["St. Louis County", "Jackson", "St. Charles", "St. Louis City", "Clay", "Greene", "Jefferson", "Boone", "Cass", "Platte", "Jasper", "Franklin", "Cape Girardeau", "Buchanan", "Cole"],
  "MT": ["Yellowstone", "Missoula", "Gallatin", "Flathead", "Cascade", "Lewis and Clark", "Silver Bow", "Ravalli", "Lake", "Lincoln", "Deer Lodge", "Hill", "Park", "Glacier", "Fergus"],
  "NE": ["Douglas", "Lancaster", "Sarpy", "Hall", "Buffalo", "Scotts Bluff", "Madison", "Lincoln", "Dodge", "Platte", "Dakota", "Gage", "Adams", "Cass", "Washington"],
  "NV": ["Clark", "Washoe", "Carson City", "Lyon", "Elko", "Nye", "Douglas", "Churchill", "Humboldt", "White Pine", "Pershing", "Lander", "Mineral", "Lincoln", "Storey", "Eureka", "Esmeralda"],
  "NH": ["Hillsborough", "Rockingham", "Merrimack", "Strafford", "Grafton", "Cheshire", "Belknap", "Carroll", "Sullivan", "Coos"],
  "NJ": ["Bergen", "Middlesex", "Essex", "Hudson", "Monmouth", "Ocean", "Union", "Camden", "Passaic", "Morris", "Mercer", "Somerset", "Burlington", "Gloucester", "Atlantic", "Cumberland", "Cape May", "Sussex", "Hunterdon", "Warren", "Salem"],
  "NM": ["Bernalillo", "Doña Ana", "Sandoval", "San Juan", "Santa Fe", "Valencia", "Chaves", "Lea", "Otero", "Eddy", "McKinley", "Curry", "Grant", "Rio Arriba", "San Miguel"],
  "NY": ["Kings", "Queens", "New York", "Suffolk", "Bronx", "Nassau", "Westchester", "Erie", "Monroe", "Richmond", "Onondaga", "Orange", "Rockland", "Albany", "Dutchess", "Saratoga", "Oneida", "Niagara", "Broome", "Ulster"],
  "NC": ["Mecklenburg", "Wake", "Guilford", "Forsyth", "Cumberland", "Durham", "Buncombe", "Union", "Gaston", "New Hanover", "Cabarrus", "Onslow", "Johnston", "Catawba", "Pitt", "Iredell", "Orange", "Robeson", "Rowan", "Alamance"],
  "ND": ["Cass", "Burleigh", "Grand Forks", "Ward", "Williams", "Stark", "Morton", "Stutsman", "Richland", "Rolette", "Barnes", "Mountrail", "Walsh", "McKenzie", "Ramsey"],
  "OH": ["Cuyahoga", "Franklin", "Hamilton", "Summit", "Montgomery", "Lucas", "Butler", "Stark", "Lorain", "Warren", "Clermont", "Lake", "Mahoning", "Trumbull", "Delaware", "Greene", "Medina", "Portage", "Licking", "Fairfield"],
  "OK": ["Oklahoma", "Tulsa", "Cleveland", "Canadian", "Comanche", "Rogers", "Creek", "Wagoner", "Pottawatomie", "Garfield", "Muskogee", "Payne", "Washington", "Carter", "McClain"],
  "OR": ["Multnomah", "Washington", "Clackamas", "Lane", "Marion", "Jackson", "Deschutes", "Linn", "Douglas", "Yamhill", "Benton", "Josephine", "Polk", "Umatilla", "Klamath"],
  "PA": ["Philadelphia", "Allegheny", "Montgomery", "Bucks", "Delaware", "Chester", "Lancaster", "York", "Berks", "Lehigh", "Westmoreland", "Northampton", "Lackawanna", "Luzerne", "Dauphin", "Washington", "Erie", "Butler", "Cumberland", "Beaver"],
  "RI": ["Providence", "Kent", "Washington", "Newport", "Bristol"],
  "SC": ["Greenville", "Richland", "Charleston", "Horry", "Spartanburg", "Lexington", "York", "Anderson", "Berkeley", "Beaufort", "Aiken", "Florence", "Sumter", "Orangeburg", "Dorchester"],
  "SD": ["Minnehaha", "Pennington", "Lincoln", "Brown", "Brookings", "Codington", "Lawrence", "Davison", "Yankton", "Meade", "Union", "Hughes", "Clay", "Beadle", "Roberts"],
  "TN": ["Shelby", "Davidson", "Knox", "Hamilton", "Rutherford", "Williamson", "Sumner", "Montgomery", "Wilson", "Blount", "Washington", "Sullivan", "Madison", "Maury", "Greene"],
  "TX": ["Harris", "Dallas", "Tarrant", "Bexar", "Travis", "Collin", "Denton", "El Paso", "Fort Bend", "Hidalgo", "Montgomery", "Williamson", "Cameron", "Nueces", "Bell", "Galveston", "Brazoria", "Webb", "Lubbock", "Jefferson", "McLennan", "Brazos", "Hays", "Smith", "Ellis", "Johnson", "Guadalupe", "Ector", "Midland", "Wichita"],
  "UT": ["Salt Lake", "Utah", "Davis", "Weber", "Washington", "Cache", "Summit", "Tooele", "Iron", "Uintah", "Box Elder", "Sanpete", "Carbon", "Duchesne", "Wasatch"],
  "VT": ["Chittenden", "Rutland", "Washington", "Windsor", "Franklin", "Windham", "Bennington", "Addison", "Orange", "Caledonia", "Lamoille", "Orleans", "Essex", "Grand Isle"],
  "VA": ["Fairfax County", "Prince William", "Virginia Beach", "Henrico", "Chesterfield", "Loudoun", "Chesapeake", "Norfolk", "Arlington", "Richmond City", "Newport News", "Hampton", "Alexandria", "Suffolk", "Spotsylvania", "Stafford", "Roanoke City", "Albemarle", "Portsmouth", "James City"],
  "WA": ["King", "Pierce", "Snohomish", "Spokane", "Clark", "Thurston", "Kitsap", "Whatcom", "Yakima", "Benton", "Cowlitz", "Franklin", "Grant", "Skagit", "Lewis"],
  "WV": ["Kanawha", "Berkeley", "Cabell", "Wood", "Monongalia", "Raleigh", "Harrison", "Mercer", "Putnam", "Ohio", "Marion", "Jefferson", "Hancock", "Wayne", "Fayette"],
  "WI": ["Milwaukee", "Dane", "Waukesha", "Brown", "Racine", "Outagamie", "Kenosha", "Winnebago", "Rock", "Washington", "Eau Claire", "La Crosse", "Marathon", "Fond du Lac", "Sheboygan"],
  "WY": ["Laramie", "Natrona", "Campbell", "Sweetwater", "Fremont", "Sheridan", "Albany", "Park", "Lincoln", "Uinta", "Carbon", "Teton", "Converse", "Goshen", "Big Horn"],
  "DC": ["District of Columbia"],
  "AS": ["Eastern District", "Western District"],
  "GU": ["Guam"],
  "MP": ["Northern Islands", "Rota", "Saipan", "Tinian"],
  "PR": ["San Juan", "Bayamón", "Carolina", "Ponce", "Caguas", "Guaynabo", "Arecibo", "Mayagüez", "Trujillo Alto", "Toa Baja"],
  "VI": ["St. Croix", "St. Thomas", "St. John"]
};